title: COONDITION:BLACK
baseURL: /
params:
  palette: black
  header:
    title: CONDITION:BLACK
    logo_img: images/logo.png
    has_nav: true
    nav_links:
      - label: Home
        url: /
      - label: Services
        url: /services
      - label: Research
        url: /research
      - label: Style Guide
        url: /style-guide
      - label: Clients
        url: /signup
        primary: true
  footer:
    logo_img: images/logo_alt.png
    tagline: Research with integrity, Security without compromise.
    has_nav: true
    nav_title: Organization
    nav_links:
      - label: About Us
        url: /about
      - label: Blog
        url: /blog
      - label: Volunteers
        url: signup
      - label: Contact
        url: /contact
    has_social: true
    social_title: Community
    social_links:
      - label: Twitter
        url: 'https://twitter.com/'
        new_window: true
      - label: Instagram
        url: 'https://www.instagram.com/'
        new_window: true
      - label: LinkedIn
        url: 'https://www.linkedin.com/'
        new_window: true
    has_subscribe: true
    subscribe_title: Subscribe
    subscribe_content: Stay up to date with our research (No Spam).
    content: '&copy; CONDITION:BLACK. All rights reserved.'
    links:
      - label: Research with integrity, Security without compromise.
        url: 'https://condition.black'
        new_window: true
disableKinds:
  - RSS
  - taxonomy
  - taxonomyTerm
